### ISSUE TITLE
Usage of TestDataLoader for different groovy scripts, which use same names for objects of same, or different types is not possible

### ISSUE THREAD

**Issue by dadrus** [triologygmbh/test-data-loader#8]
First of all, thank you for a really great tool!

I see however some limitations. One of them is the inability to use same names for objects (even for different types) from different independent scripts. This is due to the implementation of `EntityBuilder` as singleton. What is the idea behind that?

What speaks against outsourcing of the DSL implementation into a stand-alone delegate object and let `EntityBuilder` just "wire" all together?

E.g. (code snip from `EntityBuilder`):
```groovy
// ...
protected void buildEntities(Reader entityDefinitionReader) {
    DelegatingScript script = createExecutableScriptFromEntityDefinition(entityDefinitionReader)
    script.setDelegate(new EntityBuilderDSL()); // instead of "this"
    script.run()
}
// ...
```

If you like I can create a pull request to discuss a possible implementation.

**Comment by schnatterer** [comment]
Hi @dadrus,

thanks for your input! We're happy to review your PRs.

We are using test-data-loader in multiple projects and plan to continue development in the future. 
For example, we're planning to deploy it to maven central in soon. 
Right now, we're just a bit busy in our projects, so please be patient.

I just bootstrapped test-data-loader in [our Jenkins](https://opensource.triology.de/jenkins/job/triologygmbh-github/job/test-data-loader/). Your PRs should be picked up by it shortly after creation. We don't have SonarQube for our GitHub Organization just yet, so for now, please keep an eye on your code coverage, etc.
Looking forward to your PR.

**Comment by dadrus** [comment]
Hi @schnatterer. Are there any chances, that PR #10 is going to be reviewed?

**Comment by pczora** [comment]
Hi @dadrus. I would be happy to review the PR, but, as you stated in PR #10 yourself 

1. it does implement features based on two different issues (#8 and #9)
2. it is WIP

Could you please clarify whether it is still WIP? Additionally, could you please create one pull request per issue, allowing us to review (and accept) them separately?
Thank you for your help!

**Comment by dadrus** [comment]
Hi @pczora. By WIP I meant, it is an initial implementation of the referenced ideas, which (the implementation) I would like to discuss with you guys to develop it further. This is also the reason for the longer open topics paragraph in my description of the PR.

Even this PR shows a possible implementation of #8 and #9 it mainly addresses #8. Solution for #9 is just a "side effect". Because of this please consider reviewing the PR as a way to address #8. Depending on your finding/ideas, I/we could develop the PR until it suits our common imagination and then integrate into your code base. If this approach is not acceptable for you - c'est la vie. I will reinvent the wheel by myself then:)

**Comment by pczora** [comment]
Hello @dadrus,

we would be happy to incorporate your ideas into the test data loader. Please feel free to add another PR containing non-WIP code realizing your proposals :)

**Comment by dadrus** [comment]
Please checkout #10 again. It is not a WIP PR any more.
